import { supabase } from './supabase'
const requireClient=()=>{if(!supabase)throw new Error('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env.local.');return supabase}
export async function getSession(){if(!supabase)return null;const {data,error}=await supabase.auth.getSession();if(error)throw error;return data.session}
export function onAuthStateChange(cb){if(!supabase)return {data:{subscription:{unsubscribe(){}}}};return supabase.auth.onAuthStateChange(cb)}
export async function signInWithPassword(email,password){const {data,error}=await requireClient().auth.signInWithPassword({email,password});if(error)throw error;return data}
export async function signUpWithPassword(email,password,fullName){const {data,error}=await requireClient().auth.signUp({email,password,options:{data:{full_name:fullName}}});if(error)throw error;return data}
export async function signOut(){if(!supabase)return;const {error}=await supabase.auth.signOut();if(error)throw error}
export async function getCatalog({search='',genre=null}={}){if(!supabase)return[];let q=supabase.from('movies').select('id,title,description,poster_url,backdrop_url,trailer_url,video_url,release_year,duration_minutes,genre,language,is_featured,is_original,is_published').eq('is_published',true).order('is_featured',{ascending:false}).order('release_year',{ascending:false});if(genre&&genre!=='All')q=q.eq('genre',genre);if(search.trim())q=q.or(`title.ilike.%${search.trim()}%,description.ilike.%${search.trim()}%`);const {data,error}=await q;if(error)throw error;return data??[]}
export function catalogToUiMovies(rows){return rows.map((m,i)=>({id:m.id||i+1,dbId:m.id,title:m.title,year:m.release_year||new Date().getFullYear(),genre:m.genre||'Drama',duration:m.duration_minutes?`${Math.floor(m.duration_minutes/60)}h ${String(m.duration_minutes%60).padStart(2,'0')}m`:'—',image:m.poster_url||m.backdrop_url||'',description:m.description||'',videoUrl:m.video_url||'',trailerUrl:m.trailer_url||'',isFeatured:!!m.is_featured,isOriginal:!!m.is_original}))}
export async function getRemoteWatchlist(userId){const {data,error}=await requireClient().from('watchlist').select('id,movie_id,series_id,created_at,movies(id,title,poster_url)').eq('user_id',userId).order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function addToWatchlist(userId,movieDbId){const {data,error}=await requireClient().from('watchlist').insert({user_id:userId,movie_id:movieDbId}).select().single();if(error)throw error;return data}
export async function removeFromWatchlist(userId,movieDbId){const {error}=await requireClient().from('watchlist').delete().eq('user_id',userId).eq('movie_id',movieDbId);if(error)throw error}
export async function getWatchHistory(userId){const {data,error}=await requireClient().from('watch_history').select('id,movie_id,episode_id,progress_seconds,completed,last_watched_at,movies(id,title,poster_url,backdrop_url,release_year,duration_minutes,genre,description,video_url)').eq('user_id',userId).order('last_watched_at',{ascending:false}).limit(20);if(error)throw error;return data??[]}
export async function upsertWatchProgress(userId,movieDbId,progressSeconds,completed=false){const {data,error}=await requireClient().from('watch_history').upsert({user_id:userId,movie_id:movieDbId,progress_seconds:Math.max(0,Math.floor(progressSeconds)),completed,last_watched_at:new Date().toISOString()},{onConflict:'user_id,movie_id'}).select().single();if(error)throw error;return data}
export async function getProfile(userId){const {data,error}=await requireClient().from('profiles').select('*').eq('id',userId).maybeSingle();if(error)throw error;return data}
export async function updateProfile(userId,updates){const {data,error}=await requireClient().from('profiles').update(updates).eq('id',userId).select().single();if(error)throw error;return data}
export async function getNotifications(userId){const {data,error}=await requireClient().from('notifications').select('id,title,message,type,is_read,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(20);if(error)throw error;return data??[]}
export async function markNotificationRead(userId,id){const {error}=await requireClient().from('notifications').update({is_read:true}).eq('id',id).eq('user_id',userId);if(error)throw error}
export async function getPlans(){if(!supabase)return[];const {data,error}=await supabase.from('subscription_plans').select('*').eq('is_active',true).order('price_monthly');if(error)throw error;return data??[]}
export async function getMySubscription(userId){const {data,error}=await requireClient().from('subscriptions').select('id,status,started_at,current_period_start,current_period_end,plan_id,subscription_plans(id,name,price_monthly,video_quality,max_profiles,max_devices,ads_supported)').eq('user_id',userId).in('status',['trialing','active','past_due']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
export async function getCreatorProfile(userId){const {data,error}=await requireClient().from('creator_profiles').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;return data}
export async function getCreatorSubmissions(creatorId){const {data,error}=await requireClient().from('film_submissions').select('*').eq('creator_id',creatorId).order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function createFilmSubmission(creatorId,submission){const {data,error}=await requireClient().from('film_submissions').insert({creator_id:creatorId,...submission}).select().single();if(error)throw error;return data}
export async function updateCreatorProfile(userId,updates){const {data,error}=await requireClient().from('creator_profiles').upsert({user_id:userId,...updates},{onConflict:'user_id'}).select().single();if(error)throw error;return data}
export async function getSeriesCatalog(){if(!supabase)return[];const {data,error}=await supabase.from('series').select('*').eq('is_published',true).order('is_featured',{ascending:false}).order('release_year',{ascending:false});if(error)throw error;return data??[]}
export async function getEpisodes(seriesId){const {data,error}=await requireClient().from('episodes').select('*').eq('series_id',seriesId).order('season_number').order('episode_number');if(error)throw error;return data??[]}
export async function getMovieRatings(movieDbId,userId){if(!supabase||!movieDbId)return{average:null,count:0,mine:null};const {data,error}=await supabase.from('ratings').select('rating,user_id').eq('movie_id',movieDbId);if(error)throw error;const rows=data??[];const count=rows.length;const average=count?Math.round((rows.reduce((sum,r)=>sum+Number(r.rating),0)/count)*10)/10:null;const mine=userId?rows.find(r=>r.user_id===userId)?.rating??null:null;return{average,count,mine}}
export async function getRatingsSummary(){if(!supabase)return{};const {data,error}=await supabase.from('ratings').select('movie_id,rating');if(error)throw error;const byMovie={};for(const row of data??[]){if(!byMovie[row.movie_id])byMovie[row.movie_id]={sum:0,count:0};byMovie[row.movie_id].sum+=Number(row.rating);byMovie[row.movie_id].count+=1}const summary={};for(const id of Object.keys(byMovie)){const {sum,count}=byMovie[id];summary[id]={average:Math.round((sum/count)*10)/10,count}}return summary}
export async function upsertMovieRating(userId,movieDbId,rating){const {data,error}=await requireClient().from('ratings').upsert({user_id:userId,movie_id:movieDbId,rating,updated_at:new Date().toISOString()},{onConflict:'user_id,movie_id'}).select().single();if(error)throw error;return data}
