import { useEffect, useState } from 'react'
import { LogIn, LogOut, Plus, Search, Heart } from 'lucide-react'
import { getSession, onAuthStateChange, signInWithPassword, signUpWithPassword, signOut, getCatalog, catalogToUiMovies, getRemoteWatchlist, addToWatchlist, removeFromWatchlist } from './lib/platform'

export default function ConnectedApp() {
  const [user,setUser]=useState(null),[items,setItems]=useState([]),[list,setList]=useState(new Set()),[q,setQ]=useState(''),[auth,setAuth]=useState(false),[error,setError]=useState('')
  useEffect(()=>{getSession().then(s=>setUser(s?.user||null)).catch(()=>{});const x=onAuthStateChange((_,s)=>setUser(s?.user||null));return()=>x?.data?.subscription?.unsubscribe?.()},[])
  useEffect(()=>{getCatalog().then(r=>setItems(catalogToUiMovies(r))).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(!user)return;getRemoteWatchlist(user.id).then(r=>setList(new Set(r.map(x=>x.movies?.catalog_key||x.movie_id)))).catch(e=>setError(e.message))},[user])
  const toggle=async m=>{if(!user){setAuth(true);return}try{if(list.has(m.id)||list.has(m.dbId)){await removeFromWatchlist(user.id,m.dbId);setList(s=>{let n=new Set(s);n.delete(m.id);n.delete(m.dbId);return n})}else{await addToWatchlist(user.id,m.dbId);setList(s=>new Set(s).add(m.id))}}catch(e){setError(e.message)}}
  const shown=items.filter(m=>`${m.title} ${m.genre} ${m.description}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="app"><nav className="navbar"><button className="logo">RWANDA<span>FLIX</span></button><div className="nav-links"><button>Home</button><button onClick={()=>document.getElementById('catalog')?.scrollIntoView()}>Movies & Series</button><button onClick={()=>document.getElementById('my-list')?.scrollIntoView()}>My List ({list.size})</button></div><div className="nav-right"><label className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search RwandaFlix"/></label>{user?<button className="icon-btn" onClick={()=>signOut().catch(e=>setError(e.message))}><LogOut size={18}/></button>:<button className="btn primary" onClick={()=>setAuth(true)}><LogIn size={16}/> Sign In</button>}</div></nav><header className="hero"><div className="hero-content"><div className="eyebrow">🇷🇼 RwandaFlix · Live catalog</div><h1>Stories from <span>Rwanda.</span></h1><p>Rwandan stories connected to your real Supabase catalog.</p></div></header><main id="catalog" className="browse-page"><div className="page-heading"><div><div className="eyebrow">Catalog</div><h1>Movies & Series</h1><p>{user?'Your account is connected.':'Sign in to save titles to your account.'}</p></div></div>{shown.length?<div className="browse-grid">{shown.map(m=><article className="movie-card" key={m.dbId||m.id}><img src={m.image} alt={m.title}/><div className="movie-overlay"><strong>{m.title}</strong><span>{m.year} · {m.genre} · {m.duration}</span><div className="card-actions"><button onClick={()=>alert(`Playback ready for ${m.title}`)}>▶</button><button className="dark-action" onClick={()=>toggle(m)}>{list.has(m.id)||list.has(m.dbId)?<Heart size={16} fill="currentColor"/>:<Plus size={16}/>}</button></div></div></article>)}</div>:<div className="empty-state"><Search size={40}/><h2>No titles found</h2><p>Try another search.</p></div>}</main><section id="my-list" className="section browse-page"><div className="section-header"><h2><Heart size={20}/> My List</h2></div><p>{user?`${list.size} title${list.size===1?'':'s'} saved to your Supabase account.`:'Sign in to use My List.'}</p></section>{error&&<div className="toast">{error}</div>}{auth&&<Auth onClose={()=>setAuth(false)}/>}</div>
}
function Auth({onClose}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{if(mode==='login')await signInWithPassword(email,password);else await signUpWithPassword(email,password,name);onClose()}catch(x){setError(x.message)}};return <div className="modal-backdrop"><div className="auth-modal"><button className="modal-close" onClick={onClose}>×</button><h2>{mode==='login'?'Sign in':'Create account'}</h2><form onSubmit={submit}>{mode==='signup'&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input required minLength="6" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/>{error&&<p className="form-error">{error}</p>}<button className="btn primary">{mode==='login'?'Sign In':'Create Account'}</button></form><button className="switch-auth" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create an account':'Already have an account?'}</button></div></div>}
